// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2kbnhn_Q7TLgOE5SHXQRMVv_cd8gIrR0',
    appId: '1:32467926513:web:bf9083d0e7bf09cd1d1850',
    messagingSenderId: '32467926513',
    projectId: 'weatherapp-14b11',
    authDomain: 'weatherapp-14b11.firebaseapp.com',
    storageBucket: 'weatherapp-14b11.appspot.com',
    measurementId: 'G-C4TBZDXJCF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKrCQlMpGDwvBicWuZgM0Nsy6WILcVaeM',
    appId: '1:32467926513:android:c490f9a57bc173131d1850',
    messagingSenderId: '32467926513',
    projectId: 'weatherapp-14b11',
    storageBucket: 'weatherapp-14b11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCRueFE_OBwyLTdkeRwqXTY8sjT0vRsNk',
    appId: '1:32467926513:ios:746a9c38d810df291d1850',
    messagingSenderId: '32467926513',
    projectId: 'weatherapp-14b11',
    storageBucket: 'weatherapp-14b11.appspot.com',
    iosBundleId: 'com.example.weatherMachine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCRueFE_OBwyLTdkeRwqXTY8sjT0vRsNk',
    appId: '1:32467926513:ios:55f4fa7e7507e55e1d1850',
    messagingSenderId: '32467926513',
    projectId: 'weatherapp-14b11',
    storageBucket: 'weatherapp-14b11.appspot.com',
    iosBundleId: 'com.example.weatherMachine.RunnerTests',
  );
}
